### ISSUE TITLE
ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by xuala69** [cdnbye/flutter-p2p-engine#6]
I tried running the example and get the below errors on the first run

`E/MethodChannel#cdnbye(18718): Failed to handle method call
E/MethodChannel#cdnbye(18718): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#cdnbye(18718): 	at com.cdnbye.cdnbye.CdnbyeMethodHandler.onMethodCall(CdnbyeMethodHandler.java:100)
E/MethodChannel#cdnbye(18718): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#cdnbye(18718): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#cdnbye(18718): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#cdnbye(18718): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#cdnbye(18718): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#cdnbye(18718): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#cdnbye(18718): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#cdnbye(18718): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#cdnbye(18718): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#cdnbye(18718): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

I'm using Flutter (Channel stable, 2.2.3, on Linux, locale en_GB.UTF-8) and have no issue with creating/running other projects or create new ones. Every page I navigate to (Live Streaming + VOD Streaming) gives another error .

**Comment by mjl0602** [comment]
We fixed it on version 1.2.1.
